# Generated by Django 2.2.6 on 2019-11-27 12:40

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviepage',
            name='premiere',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moviepage',
            name='showEndDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='moviepage',
            name='showStartDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='moviepage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.TextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('quotation', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.TextBlock()), ('author', wagtail.core.blocks.CharBlock())]))], blank=True, null=True),
        ),
    ]
