# Generated by Django 2.2.6 on 2020-01-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20191215_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='KijkWijzerClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=36)),
                ('icon', models.CharField(max_length=36)),
            ],
        ),
        migrations.AddField(
            model_name='moviepage',
            name='classifications',
            field=models.ManyToManyField(to='home.KijkWijzerClassification'),
        ),
    ]
