# Generated by Django 2.2.6 on 2020-07-29 09:13

from django.db import migrations, models
import home.models
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200120_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.TextBlock()), ('image', home.models.MyImageChooserBlock())]),
        ),
        migrations.AlterField(
            model_name='moviedate',
            name='date',
            field=models.DateTimeField(default=home.models.default_movie_date, verbose_name='Show Date'),
        ),
        migrations.AlterField(
            model_name='moviepage',
            name='classifications',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='home.KijkWijzerClassification'),
        ),
    ]
