# Generated by Django 2.2.6 on 2020-09-03 18:49

from django.db import migrations
import home.models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200729_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.TextBlock()), ('link', wagtail.core.blocks.URLBlock()), ('movieList', wagtail.core.blocks.BooleanBlock()), ('image', home.models.MyImageChooserBlock())], default=''),
            preserve_default=False,
        ),
    ]
