# Generated by Django 2.2.6 on 2019-11-15 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0008_filmpage_doublebillfilm'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmpage',
            name='filmBack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
