# Generated by Django 2.2.6 on 2021-06-22 11:44

from django.db import migrations
import home.models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homepage_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviedate',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.TextBlock()), ('image', home.models.MyImageChooserBlock()), ('richContent', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'ol', 'ul', 'hr', 'bold', 'italic', 'link']))]),
        ),
    ]
