# Generated by Django 2.2.6 on 2020-08-11 12:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BouncedEmailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailAddress', models.EmailField(max_length=254)),
                ('isProcessed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MailServerConnection',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('clazzName', models.CharField(max_length=125)),
                ('data', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=48, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SharedMailTemplate',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('clazzName', models.CharField(max_length=125)),
                ('data', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MailSender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48, unique=True)),
                ('mailServerConnection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jimbo_mail.MailServerConnection')),
            ],
        ),
        migrations.CreateModel(
            name='MailQueue',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('clazzName', models.CharField(max_length=125)),
                ('data', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('senderName', models.CharField(max_length=64)),
                ('mailFrom', models.EmailField(max_length=254)),
                ('mailTo', models.EmailField(max_length=254)),
                ('userId', models.CharField(blank=True, max_length=64, null=True)),
                ('organisationId', models.CharField(blank=True, max_length=64, null=True)),
                ('unsubscribeUrl', models.CharField(blank=True, max_length=150, null=True)),
                ('nrOfSendAttempts', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('RE', 'Ready'), ('SE', 'Sending'), ('FR', 'Send failed retry'), ('FN', 'Send failed, no retry')], default='RE', max_length=3)),
                ('sentAt', models.DateTimeField(blank=True, null=True)),
                ('preferredSendTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleteAfterSend', models.BooleanField(default=False)),
                ('sendResponse', models.TextField(null=True)),
                ('sharedMailTemplate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jimbo_mail.SharedMailTemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
