# Generated by Django 2.2.6 on 2020-08-11 12:08

from django.db import migrations, models
import django.db.models.deletion
import tickets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0007_auto_20200729_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.CharField(editable=False, max_length=36, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('nrOfSeats', models.IntegerField(choices=[(1, 'OneSeat'), (2, 'DuoSeat')])),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('open', 'open'), ('accepted', 'accepted'), ('rejected', 'rejected')], max_length=24)),
                ('ticketSendStatus', models.CharField(choices=[('no-ticket', 'no-ticket'), ('request-ticket-create', 'request-ticket-create'), ('ticket-create-start', 'ticket-create-start'), ('ticket-created', 'ticket-created'), ('request-ticket-send', 'request-ticket-send'), ('ticket-sent', 'ticket-sent')], default='no-ticket', max_length=24)),
                ('lastStatusUpdate', models.DateTimeField(auto_now=True)),
                ('paymentUrl', models.CharField(blank=True, max_length=256, null=True)),
                ('paymentId', models.CharField(blank=True, max_length=256, null=True)),
                ('ticketPdf', models.FileField(blank=True, max_length=200, null=True, upload_to=tickets.models.generate_ticket_filename)),
                ('ticketRequestData', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('referenceNumber', models.IntegerField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=6, null=True)),
                ('mailConfirmationId', models.CharField(blank=True, max_length=36, null=True, unique=True)),
                ('movieDate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Moviedate')),
            ],
        ),
        migrations.CreateModel(
            name='TicketStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'open'), ('canceled', 'canceled'), ('pending', 'pending'), ('authorized', 'authorized'), ('expired', 'expired'), ('failed', 'failed'), ('payed', 'payed'), ('refunded', 'refunded'), ('sended-vmail', 'sended-vmail'), ('email-verified', 'email-verified')], max_length=24)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Ticket')),
            ],
        ),
    ]
